### ISSUE TITLE
Not running my tests on save

### ISSUE THREAD

**Issue by simonexmachina** [accerqueira/sublime-test-runner#3]
I think it's not running my tests on save, at least I can't see any evidence that it is.

I've configured my `Makefile` so that `make test REPORTER=tap` (in the project root directory) runs `mocha`, but when I save in Sublime nothing happens, except `[ executed ]` appears in the status bar.

I'm running Sublime Text 3 stable channel build 3059.

Thanks!

**Comment by accerqueira** [comment]
Which version of node are you using? I had problems with some older versions that would truncate piped output.

Just tested on Windows, with Sublime Text 3 build 3059, GNU Make 3.81 and node.js v0.10.24, using the following Makefile and it worked...

``` make
REPORTER ?= dot

test:
    @node ./node_modules/mocha/bin/_mocha -R $(REPORTER)

.PHONY: test
```

And had mocha installed locally on the project.
You could also install it globally and run it with "mocha -R $(REPORTER)" instead.

Can you run "make test REPORTER=tap" directly from the shell and post the output?
You can also try running "node ./node_modules/mocha/bin/_mocha -R tap" or "mocha -R tap" and checking if the output is ok.

**Comment by simonexmachina** [comment]
I'm using version 0.10.22 on a Mac.

Running `make test REPORTER=tap` definitely works in the terminal.

Here's the Makefile:

```
REPORTER ?= dot

test:
    @node ./node_modules/mocha/bin/_mocha --compilers coffee:coffee-script -R $(REPORTER)

.PHONY: test
```

And here's the output:

```
$ make test REPORTER=tap
1..1
ok 1 proxy server should accept connections
# tests 1
# pass 1
# fail 0
```

**Comment by accerqueira** [comment]
Hmmm
Do you have one of the following folders next to the Makefile?
test
tests
spec
specs

Currently, Test Runner does not look for a Makefile, it looks for one of these folders.
The reason is that you could change the testing command to something else that doesn't use make, a .bat on Windows for instance, but I probably shouldn't rely on one of those folders being present either...

The solution I can think of, is looking for a .test-runner file on the parent folders, if not found, fallback to running on the same folder as the sublime-project file, if not in a project, fallback to running on same folder as the current file.
Will try to implement and release this possible solution today.

**Comment by accerqueira** [comment]
Ended up doing another way, an easier one. hehe
Now you can setup the files it should look for, and it also looks for Makefile by default.
Could you upgrade and tell me if it works?

**Comment by simonexmachina** [comment]
Yes, I have a `test/` folder.

Have upgraded and still nothing happens when I save, although `make test` does work.

**Comment by maximeaubaret** [comment]
I have the same problem here. I've not been able to run my mocha tests.

**Comment by accerqueira** [comment]
Just tested on a Linux with node.js v0.10.22 and v0.10.25, both worked... I'll add some debug logging and ask for your help on debugging this...

**Comment by accerqueira** [comment]
Released version v1.4.0.
Although I was just going to add logging, I found and fixed some glitches that didn't affect me but were bad for ST3.
This version may fix this issue, but if it doesn't, could you do the following?
Navigate to "Preferences > Package Settings > Test Runner > Settings - User"
Paste the following lines:
{
    "log_level": "debug"
}
Save and try triggering Test Runner for your project again.

**Comment by maximeaubaret** [comment]
Thanks for the quick response.
I've upgraded Test Runner to the release 1.4.0, and set the "log_level" to "debug" value in "Preferences > Package Settings > Test Runner > Settings - User". I'm using Sublime 3 Build 3059 and Node v0.10.25.

The upgrade has not fixed the problem, and no logs are showing in the window. 

But I know for a fact that my Makefile is used, and that the 'test' rule is executed: by adding a 'say hi' command inside of the 'test' rule and setting the volume on my Mac, I can hear the sound the computer talk.

Here is my Makefile:

``` Makefile
REPORTER=tap

test:
    say 'hi'
    @./node_modules/mocha/bin/_mocha -R $(REPORTER)

.PHONY: test
```

And here are my User Settings: 

``` json
{
  "show_panel_default": true,
  "log_level": "debug"
}
```

**Comment by simonexmachina** [comment]
Yep I can confirm exactly the same for me.

**Comment by accerqueira** [comment]
I forgot to tell that the log should be on Sublime Text console and also on
a file, probably "Test Runner.TestRunner.log" inside ST3 folder.

**Comment by accerqueira** [comment]
Hmm, just discovered that if you don't have permission to write on that folder, the log wont be output at all... will change that...
I'll try to get an OSX for testing stuff...

**Comment by simonexmachina** [comment]
The log file was being written on my machine and showed me that Sublime's process doesn't have a correct path. So I've added `PATH=/usr/local/bin` at the top of my Makefile and it's now running node.

**Comment by maximeaubaret** [comment]
I'm going to try this... Let me get back to you.

**Comment by maximeaubaret** [comment]
Thanks! It finally works :)
Adding the path in my Makefile did the trick.

**Comment by accerqueira** [comment]
Awesome!
Closing this, but feel free to post if you encounter more issues.
